# Generated by Django 4.0.4 on 2022-05-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departaments',
            old_name='Departament_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='role_name',
            new_name='name',
        ),
    ]
