# Generated by Django 4.0.4 on 2022-05-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_rename_departament_name_departaments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='departament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departaments'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='departament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departaments'),
        ),
    ]
